# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Snow River Notes 钓雪记
author: Wenqin Shao (邵文钦)
email: wenqin.shao.sh@gmail.com
first_year: 2024
description: >- # this means to ignore newlines until "baseurl:"  
  A blog about life in AI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wenqinshao.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO Settings
lang: en_US
social:
  name: Wenqin Shao
  links:
    - https://github.com/wenqinshao # Add your social media links

# Google Analytics
google_analytics: G-MT8X9RM4LW

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - posts.md
  - bio.md

markdown: kramdown
kramdown:
   input: GFM
   math_engine: katex

# show excerpts on the home page (we also enforce it in our layout below)
show_excerpts: true

# use this marker inside posts to control where the abstract cuts off
# excerpt_separator: "<!--more-->"

default_license: cc-by-nc-4.0          # text/posts by default
assets_default_license: all-rights     # images/illustrations by default
code_license: MIT

footer_rights: ""

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
